### DISCUSSION TITLE
how to make footer

### DISCUSSION THREAD

**Discussion by El-Idrisi** [drknzz/GitHub-Achievements#400] [General]
i wanna make a footer, but i don't no where to start. can you guys help guys?

**Comment by mtaufik31** [comment]
So, to make a footer you need to know what kind of footer u wanna make. after u know what footer you wanna make, then u can make a footer. is my answer helping?

**Reply by El-Idrisi** [reply]
thanks for solutions, mtaufik31

**Comment by Limzen** [comment]
Here’s a simple example using HTML and CSS:

### HTML
```html
<footer>
  <p>&copy; 2024 Your Company. All rights reserved.</p>
  <ul>
    <li><a href="#about">About Us</a></li>
    <li><a href="#contact">Contact</a></li>
    <li><a href="#privacy">Privacy Policy</a></li>
  </ul>
</footer>
```

### CSS
```css
footer {
  background-color: #333;
  color: #fff;
  text-align: center;
  padding: 20px;
  position: fixed;
  bottom: 0;
  width: 100%;
}

footer ul {
  list-style-type: none;
  padding: 0;
}

footer ul li {
  display: inline;
  margin: 0 10px;
}

footer ul li a {
  color: #fff;
  text-decoration: none;
}

footer ul li a:hover {
  text-decoration: underline;
}
```

### Explanation
- The `<footer>` element is used to create the footer section.
- The `<p>` tag contains some copyright text.
- The `<ul>` list with `<li>` items holds links for common footer sections like "About Us," "Contact," and "Privacy Policy."
- The CSS styles the footer with a dark background, white text, and centers the content. It also makes the footer fixed at the bottom of the page.
